name: gym_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.0
  fl_chart: ^1.1.1
  table_calendar: ^3.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4
  patrol: ^4.1.0

flutter:
  uses-material-design: true
